name: CI Pipeline

# Тригер для виконання pipeline
on:
  push:
    branches:
      - main   # виконувати при пушах на main
  pull_request:
    branches:
      - main   # виконувати при пулл-реквестах на main

jobs:
  build:
    runs-on: windows-latest  # Виконувати на останній версії Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0'  # версія .NET, яку ви використовуєте

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Run tests
        run: dotnet test PastBeam.Tests/PastBeam.Tests.csproj --verbosity normal

      - name: Login to Azure
        uses: azure/login@v1  # Логін до Azure через Service Principal
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Publish app
        run: dotnet publish PastBeam.Presentation/PastBeam.Presentation.csproj -c Release -o publish
      
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: PastBeamPresentation20250429150142
          slot-name: production
          package: ./publish
